site_name: Cloudpie User Guide
theme:
  name: material
  custom_dir: overrides
  logo: images/cloudpie_black_logo.svg
  features:
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest    
  palette:
    scheme: default
    primary: indigo
    accent: blue
plugins:
  - render_swagger
  - search
extra_css:
  - api/custom.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences 
nav:
  - Introduction: index.md
  - Getting Access: getting-access.md
  - Understanding Cloudpie Design: understanding-cloudpie-design.md
  - Managing Users:
    - Adding new Users: adding-users.md
    - Manage existing Users: managing-users.md
  - Projects:
      - Creating a Project: project-create.md
      - Viewing Projects: projects-view.md
      - Updating a Project: project-edit.md
      - Deleting a project: project-delete.md
  - Cloud Accounts:
      - Adding cloud Credentials: cloud-credentials-add.md
      - Adding a Cloud Account: cloud-account-add.md
      - Viewing Cloud Accounts: cloud-accounts-view.md
      - Querying Cloud Accounts: cloud-accounts-querying.md
      - Updating a Cloud Account: cloud-account-update.md
      - Deleting a Cloud Account: cloud-account-delete.md
      - Managing Cloud Alerts: cloud-alerts.md
  - Workspaces:
      - Adding a Workspace: workspace-add.md
      - Deploying resources to Cloud in Workspaces: workspaces-view.md
      - Updating a Workspace: workspace-update.md
      - Deleting a Workspace: workspace-delete.md
  - AI Powered Insights: insights.md
  - Project Tasks Management: tasks.md
  - Manage API tokens: api-tokens.md
  - API Docs: api/openapi.md

copyright: "© 2025 Cloudpie. All rights reserved."